### ISSUE TITLE
Can the vibrator be repaired?  

### ISSUE THREAD

**Issue by gesangtome** [SHRP/shrp_bootable_recovery#22]
Everything looks very good, but the only vibrator does not work, I saw from the log that the corresponding sys node can no longer be found. Is it possible to provide an option to turn off the vibrator option, or to provide a new SYS node for recovery?
 
[recovery.log](https://github.com/SKYHAWK-Recovery-Project/shrp_bootable_recovery/files/4678357/recovery.log)
[dmesg.log](https://github.com/SKYHAWK-Recovery-Project/shrp_bootable_recovery/files/4678358/dmesg.log)

**Comment by Giovix92** [comment]
New commits regarding vibrators have been merged. Check 'em out and make proper edits to your tree.

**Comment by gesangtome** [comment]
@Giovix92 
That's great. I'm really excited today.

**Comment by gesangtome** [comment]
@Giovix92 
I still can't control the hardware work through the 1.2 vibrator HAL. I added 1.0 vibrator hal support based on submissions from other developers. After testing, I can obviously hear the sound of the vibrator working. I adjusted the intensity of the vibrator to the highest level. I still can't feel it through the touch, but it is indeed working.

The patch can be found here: https://github.com/SKYHAWK-Recovery-Project/shrp_bootable_recovery/pull/27

**Comment by Giovix92** [comment]
> @Giovix92
> I still can't control the hardware work through the 1.2 vibrator HAL. I added 1.0 vibrator hal support based on submissions from other developers. After testing, I can obviously hear the sound of the vibrator working. I adjusted the intensity of the vibrator to the highest level. I still can't feel it through the touch, but it is indeed working.
> 
> The patch can be found here: #27

Thank you for submitting a patch. I'll look at it tonight.

**Comment by Giovix92** [comment]
Merged pull request #27. Thank you for your contribute!
