### ISSUE TITLE
Thanks for your work. Your recovery very beautiful!

### ISSUE THREAD

**Issue by LeChenOS** [SHRP/shrp_bootable_recovery#9]
Ilike your work very much, But not friendly to Chinese users, please  add chinese language and close avb2.0 button, thanks

**Comment by epicX67** [comment]
@LeChenOS what do you mean by avb2.0 ?

**Comment by LeChenOS** [comment]
Turn off boot inspection

**Comment by LeChenOS** [comment]
AVB2.0 is used for booting, this usage adds a "vbmeta.img" image. The public key is compiled into the bootloader to verify vbmeta data, and vbmeta.img contains the signature that should be verified by this public key.

vbmeta.img contains the public key used for authentication, but vbmeta.img can only be trusted if the bootloader has verified it, just like authentication, it contains a trusted public key and a signature

**Comment by LeChenOS** [comment]
Therefore, we have two important keys in AVB, one is to verify the OEM key of vbmeta.img, and the other is to verify the verity key of other partitions (boot / system / vendor). Of course, you can use the OEM key as the verity key.

We know that the OEM key is used to verify vbmeta.img during the bootloader phase. This is not enough, we have to verify other partitions, vbmeta.img contains the public key for this purpose. Just like the verity key in avb1.0, this public key is used to verify the system, vendor partition, and boot partition. There are some differences here, avb1.0 uses the OEM key to verify the boot partition, verity key to verify the system / vendor partition, but avb2.0 uses the OEM key to verify vbmeta.img, and uses the public key included in it to verify other partitions (system / vendor / boot, etc.).

**Comment by Giovix92** [comment]
Hey,
Thanks for your kind words.
Already seen you forked our repo into your account, did you already made any implementation of that button that "closes" avb2.0? Let me know!

- Giovix92

**Comment by LeChenOS** [comment]
link

**Comment by LeChenOS** [comment]
unpack_bootimg link http://t.cn/A6zHUwg9

**Comment by LeChenOS** [comment]
[twres.zip](https://github.com/SKYHAWK-Recovery-Project/shrp_bootable_recovery/files/4352231/twres.zip)

**Comment by LeChenOS** [comment]
[twres.zip](https://github.com/SKYHAWK-Recovery-Project/shrp_bootable_recovery/files/4352235/twres.zip)
Please check the source code

**Comment by LeChenOS** [comment]
[supersu.zip](https://github.com/SKYHAWK-Recovery-Project/shrp_bootable_recovery/files/4352242/supersu.zip)
